# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-mysql-AutoTypes
version:      1.0
version_from: lib/DBD/mysql/AutoTypes.pm
installdirs:  site
requires:
    DBD::mysql:                    2.9002
    DBI:                           0
    Regexp::Common:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
